name: liepsgmbh/teaser
typeName: teaser
group: default
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: image
    type: File
    useExistingField: true
    label: 'Teaser Bild'
    required: true
    maxitems: 1
    allowed: common-image-types
    crop:
      default:
        title: 'Standard'
        allowedAspectRatios:
          '16:9':
            title: '16:9'
            value: 1.777777777777778
          '4:3':
            title: '4:3'
            value: 1.333333333333333
          '1:1':
            title: '1:1'
            value: 1
  - identifier: header
    type: Text
    useExistingField: true
    label: 'Überschrift'
    required: true
    max: 50
    placeholder: 'Geben Sie hier die Überschrift ein.'
  - identifier: bodytext
    type: Textarea
    useExistingField: true
    label: 'Teaser Text'
    required: true
    rows: 5
    placeholder: 'Geben Sie hier den Teaser-Text ein.'
  - identifier: header_link
    type: Link
    useExistingField: true
    label: 'Link'
    required: true
    placeholder: 'Geben Sie hier den Link ein.'