name: liepsgmbh/accordion
typeName: accordion
group: default
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: image_zoom
    type: Checkbox
    label: 'Kein Rand'
    useExistingField: true
    default: false
  - identifier: accordion_panels
    type: Collection
    label: 'Panels'
    required: true
    min: 1
    foreign_field: 'parent_uid'
    foreign_sortby: 'sorting'
    fields:
      - identifier: title
        type: Text
        label: 'Titel'
        required: true
      - identifier: active
        type: Checkbox
        label: 'Aufgeklappt anzeigen'
        default: false
      - identifier: hidden
        type: Checkbox
        label: 'Panel deaktivieren'
        default: false
      - identifier: content
        type: Collection
        foreign_table: tt_content
        overrideChildTca:
          columns:
            CType:
              config:
                default: text
